# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fastapi-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: fastapi
#   template:
#     metadata:
#       labels:
#         app: fastapi
#     spec:
#       containers:
#       - name: fastapi
#         image: bigodoy2/fastapi-demo:tagname # Use your existing Docker image
#                 # imagePullPolicy: Never
#         ports:
#         - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: bigodoy2/fastapi-demo:latest
          ports:
            - containerPort: 80