# apiVersion: v1
# kind: Service
# metadata:
#   name: fastapi-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: fastapi
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # This port must be in the range 30000-32767